# Number of strategies to simulate
number_strategies: 8

# Number of times (minimum) to play each strategy
# Note: the exact number depends on both the total number of
# strategies and number of players per game.
play_each_strategy: 2

# Players per game; either 3, 4, or 5.
players_per_game: 4

# Optional list of player names.
# Note: length should (at least) match number of players per game.
player_names:

# Maximum number of turns to simulate
# Note: Set to 0 for no limit
max_turns: 75

# Set initial player budget
start_budget: 90

# Smallest bidding unit
bid_unit: 10

# Trade threshold: players only trade when collecting more animals than this threshold
trade_threshold: 1

# Scoring threshold: when computing final scores, count sets above threshold as complete
score_threshold: 3

# Include remaining budget in the final score
score_budget: True

# Define animals and associated score points
animals:
    Haan:     10
    Gans:     40
    Kat:      90
    Hond:    160
    Schaap:  250
    Bok:     350
    Ezel:    500
    Varken:  650
    Koe:     800
    Paard:  1000

# Number of cards for each animal
animal_cards: 4

# Set bonuses for animals
animal_bonuses:
  Ezel: [50, 100, 200, 500]
